# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Artifact2'
    publishLocation: 'pipeline'

- task: replacetokens@5
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/_Artifact2/Artifact2/s'
    targetFiles: 'simpleec2instance.yml'
    encoding: 'auto'
    tokenPattern: 'custom'
    tokenPrefix: '#@'
    tokenSuffix: '@#'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: true
    
variables:

- group: ec2variables

- name: AvailabilityZone

  value: 'us-east-1a'

- name: InstanceType

  value: 't2.micro'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-Bharathiserviceconnection'
    regionName: 'us-east-1'
    stackName: 'simpleec2withyaml'
    templateSource: 'file'
    templateFile: 'simpleec2instance.yml'