Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: bharathibucket1
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effecct: Allow
            Principal: "*"
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'
      Bucket: !Ref MyS3Bucket
